//const boolean debug = false;     //universal debug
const boolean debug_setup = false; //setup debug
const boolean debug_loop = false;  //loop debug
const boolean debug_mode0 = false; //mode0 debug
const boolean debug_mode1 = false; //mode1 debug
const boolean debug_mode2 = false; //mode2 debug
const boolean debug_mode3 = false; //mode3 debug
const boolean debug_mode4 = false; //mode4 debug
const boolean debug_int0 = false;  //interrupt0 debug
const boolean debug_verbose = true; //this should usually be enabled
